routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\TicketController;
use App\ticket;
use App\horario;
use App\cardapio;
use App\avaliacao;
use Carbon\Carbon;

Auth::routes();

Route::get('/', function () {
  if(Auth::user()){
    if(auth()->user()->is_admin == 1){
      return redirect()->route('admin.home');
    }
    else {
      return redirect()->route('home');
    }
  }
  else{
    return view('/auth/login');
  }
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin'], function(){
  Route::resource('ticket', 'TicketController')->middleware('is_admin');
  Route::resource('horarios','HorarioController')->middleware('is_admin');
  Route::resource('cardapios','CardapioController')->middleware('is_admin');
  Route::resource('alimentos', 'AlimentoController')->middleware('is_admin');
  Route::resource('avaliacao', 'AvaliacaoController');
  Route::get('/avaliacoes/','AvaliacaoController@index_total')->name('avaliacao.index_total')->middleware('is_admin');
  Route::get('/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');
  Route::get('/relatorios', 'HomeController@relatorioCompras')->name('relatorios')->middleware('is_admin');
});

Route::group(['prefix'=>'aluno'], function(){
  Route::get('/usar_ticket', 'PedidoController@alunoUsarTicket')->name('usar');
  Route::post('/saldo_add', 'PedidoController@alunoSaldoAdd')->name('alunoSaldoAdd');
  Route::get('/comprar/{ticket}', 'PedidoController@compra')->name('comprar');
  Route::get('/avaliacoes','AvaliacaoController@indexAluno')->name('aluno.avaliacoes');
  Route::get('/pedidos','PedidoController@indexPedidos')->name('aluno.pedidos');
});















































// ?
Route::get('/giomar', function () {
    return view('giomar');
})->name('giomar');

resources/views/adminHome.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <center>
    <div>
        <div class="col-md-8">
            <div class="card"  style="width:100%; height: 100%">
                <div class="card-header" style="margin-left: 183px; height: 60px">Página do Administrador</div>
                <div class="card-body">
                     <a class="btn btn-primary"  href="{{ route('ticket.index') }}">Ticket</a>
                     <a class="btn btn-primary"  href="{{ route('cardapios.index') }}">Cardapios</a>
                     <a class="btn btn-primary"  href="{{ route('alimentos.index') }}">Alimentos</a>
                     <a class="btn btn-primary"  href="{{ route('horarios.index') }}">Horários</a>
                     <a class="btn btn-primary"  href="{{ route('relatorios') }}">Relatorios</a>
                     <a class="btn btn-primary"  href="{{ route('avaliacao.index') }}">Avaliações</a>
                  </br>
                <div style="height: 30px; margin-top: 10px">
                Bem vindo {{ Auth::user()->name }}.
                @if($horario)
                  <br>Horário de funcionamento atual: {{ $horario->inicioHora }} às {{ $horario->fimHora }}.
                @else
                  <br>Nenhum horário de funcionamento configurado.
                @endif
                </div>
                <br><strong>Menu Semanal:</strong>
                <table class="table table-bordered">
                    <tr>
                        <th>Dia</th>
                        <th>Cardápio</th>
                    </tr>
            	    <tr>
                        <td><strong>Segunda-Feira</strong></td>
                        <td>{{ $cardapio_semanal['segunda'] }}</td>
            	    </tr>
                  <tr>
                        <td><strong>Terça-Feira</strong></td>
                        <td>{{ $cardapio_semanal['terca'] }}</td>
            	    </tr>
                  <tr>
                        <td><strong>Quarta-Feira</strong></td>
                        <td>{{ $cardapio_semanal['quarta'] }}</td>
            	    </tr>
                  <tr>
                        <td><strong>Quinta-Feira</strong></td>
                        <td>{{ $cardapio_semanal['quinta'] }}</td>
            	    </tr>
                  <tr>
                        <td><strong>Sexta-Feira</strong></td>
                        <td>{{ $cardapio_semanal['sexta'] }}</td>
            	    </tr>
                  <tr>
                        <td><strong>Sábado</strong></td>
                        <td>{{ $cardapio_semanal['sabado'] }}</td>
            	    </tr>
                  <tr>
                        <td><strong>Domingo</strong></td>
                        <td>{{ $cardapio_semanal['domingo'] }}</td>
            	    </tr>
                </table>
                </div>
        </div>
    </div>
 </center>
</div>
@endsection

resources/views/alunoPedidos.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-10 margin-tb">
            <div class="pull-left" style="margin-left: 10px">
                <h2>Seus Pedidos</h2>
            </div>
        </br>
        </div>
    </div>
    </br>
    <table class="table table-bordered">
      <tr>
        <th>Descrição</th>
        <th>Valor</th>
        <th>Utilização</th>
      </tr>
    @foreach ($pedidos as $pedido)
    <tr>
        <td>
          @if($pedido['descricao_cardapio'] == NULL)

          @else
          {{ $pedido['descricao_cardapio'] }}
          @endif</td>
        <td>R${{ number_format($pedido['valor_ticket'], 2, '.', '') }}</td>
        <td>
          @if($pedido['data_de_utilizacao'])
            {{ $pedido['data_de_utilizacao'] }}
          @else
            Ticket não usado.</td>
          @endif
    </tr>
    @endforeach
    </table>
</div>
<div class="pull-right" style="margin-left: 128px">
  <a class="btn btn-secondary" href="{{ route('home') }}">Voltar</a>
</div>
@endsection

resources/views/flash-message.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($errors->any())
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert">×</button>
	Please check the form below for errors
</div>
@endif

resources/views/giomar.blade.php
<div style=" background-size: cover;
background-image:url('{{ asset('img/img.jpeg') }}');
height:149%">

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card"  style="width:100%; height: 100%">
        <div>
            <div style="margin-left: 440px" class="card-header">Página Inicial</div>
            <table class="table table-bordered">
              <tr>
                <td>
                <div style="margin-left: 20px">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Bem vindo {{ Auth::user()->name }}.

                    <form action="{{ route('alunoSaldoAdd') }}" method="POST">
                    @csrf
                        Seu saldo é R${{ number_format(Auth::user()->saldo, 2) }}
                        <input class="form-control" style="width: 120px; height:40px;"  name="saldoAdd" placeholder="Saldo"></input>
                      </br>
                        <button type="submit" class="btn btn-primary">Adicionar Saldo</button>
                      <br>
                    </form>
                </div>
                </td>
                <td>
                <div style="margin-right: 20px;margin-left: 20px ">
                      Custo do ticket atual: R${{ $ticketValor }}. </br> Limite de compras: {{ $ticket['limite_compra'] }}.

                      <form action="{{ route('comprar', $ticket) }}" method="get">
                      @csrf
                      <input type="number" id="quantidade" name="quantidade" min="1" width= "10px" placeholder="Quantidade">

                        @if ($ticket->estoque >= 1)
                          <button type="submit" class="btn btn-primary">Comprar</button>
                        @else
                          Ticket fora de estoque.
                        @endif
                      </form>
                </div>
                </td>
                <td>
                <div style="margin-top: -23px">
                        @if($horario_funcionamento)
                          <br>Horário de Funcionamento: {{ $horario_funcionamento->inicioHora }} às {{ $horario_funcionamento->fimHora }}.
                          <br>Limite de uso de ticket por dia: {{ $ticket['limite_uso'] }}.
                          <br>Cardápio de Hoje: {{ $cardapio }}</br>
                          <div class = "row-center">
                            <a class="btn btn-primary" href="{{ route('usar') }}">Usar Ticket</a>
                          </div>
                        @else
                          O Restaurante Universitário está fora de funcionamento.
                        @endif
                </div>
                </td>
              </tr>
            </table>
            <div style="margin-left: 350px" class="card-header">Últimas Compras
                <a class="btn btn-primary" href="{{ route('aluno.pedidos') }}">Mostrar Todas</a>
                </div>
                <table class="table table-bordered">
                  <tr>
                    <th>Descrição</th>
                    <th>Valor</th>
                    <th>Utilização</th>
                  </tr>
                @foreach ($pedidos as $pedido)
                <tr>
                    <td>
                      @if($pedido['descricao_cardapio'] == NULL)

                      @else
                      {{ $pedido['descricao_cardapio'] }}
                      @endif</td>
                    <td>R${{ number_format($pedido['valor_ticket'], 2, '.', '') }}</td>
                    <td>
                      @if($pedido['data_de_utilizacao'])
                        {{ $pedido['data_de_utilizacao'] }}
                      @else
                        Ticket não usado.</td>
                      @endif
                </tr>
                @endforeach
                </table>
    </div>

            <div style="margin-left: 330px" class="card-header">Avaliacões Pendentes
                <a class="btn btn-primary" href="{{ route('aluno.avaliacoes') }}">Mostrar Todas</a>
            </div>
            <table class="table table-bordered">
                <tr>
                    <th>Data</th>
                    <th>Descrição</th>
                    <th></th>
                </tr>
                @foreach ($avaliacoes_pendentes as $avaliacao)
                @csrf
                  <tr>
                      <td>{{ $avaliacao->data }}</td>
                      <td>{{ $avaliacao->descricao }}</td>
                      <td><a class="btn btn-primary" href="{{ route('avaliacao.edit', $avaliacao->id) }}">Avaliar</a></td>
                    </tr>
                @endforeach
            </table>
    </div>
</div>
@endsection