routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\TicketController;
use App\ticket;
use App\horario;
use App\cardapio;
use App\avaliacao;
use Carbon\Carbon;

Auth::routes();

Route::get('/', function () {
  if(Auth::user()){
    if(auth()->user()->is_admin == 1){
      return redirect()->route('admin.home');
    }
    else {
      return redirect()->route('home');
    }
  }
  else{
    return view('/auth/login');
  }
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin'], function(){
  Route::resource('ticket', 'TicketController')->middleware('is_admin');
  Route::resource('horarios','HorarioController')->middleware('is_admin');
  Route::resource('cardapios','CardapioController')->middleware('is_admin');
  Route::resource('alimentos', 'AlimentoController')->middleware('is_admin');
  Route::resource('avaliacao', 'AvaliacaoController');
  Route::get('/avaliacoes/','AvaliacaoController@index_total')->name('avaliacao.index_total')->middleware('is_admin');
  Route::get('/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');
  Route::get('/relatorios', 'HomeController@relatorioCompras')->name('relatorios')->middleware('is_admin');
});

Route::group(['prefix'=>'aluno'], function(){
  Route::get('/usar_ticket', 'PedidoController@alunoUsarTicket')->name('usar');
  Route::post('/saldo_add', 'PedidoController@alunoSaldoAdd')->name('alunoSaldoAdd');
  Route::get('/comprar/{ticket}', 'PedidoController@compra')->name('comprar');
  Route::get('/avaliacoes','AvaliacaoController@indexAluno')->name('aluno.avaliacoes');
  Route::get('/pedidos','PedidoController@indexPedidos')->name('aluno.pedidos');
});















































// ?
Route::get('/giomar', function () {
    return view('giomar');
})->name('giomar');

app/horario.php
<?php
namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class horario extends Eloquent
{
	protected $connection = 'mongodb';
	protected $collection = 'horarios';


  protected $fillable = ['inicioData', 'fimData', 'inicioHora', 'fimHora'];
}

app/Http/Controllers/HorarioController.php
<?php

namespace App\Http\Controllers;

use App\horario;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class HorarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $horarios = collect(horario::all())->sortBy(function($horario, $key){
        return Carbon::createFromFormat('d/m', $horario->inicioData);
      });
      return view('horarios.index',compact('horarios'))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\horario  $horario
     * @return \Illuminate\Http\Response
     */
    public function edit(horario $horario)
    {
        return view('horarios.edit',compact('horario'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\horario  $horario
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, horario $horario)
    {
      request()->validate([
        'inicioData' => 'required|date_format:d/m',
        'fimData' => 'required|date_format:d/m',
        'inicioHora' => 'required|date_format:H:i',
        'fimHora' => 'required|date_format:H:i',
      ]);

      if($this->data_legitima($request)){
        $horario->update($request->all());

        return redirect()->route('horarios.index')->with('success','Horario atualizado com sucesso');
      }
      else {
        return redirect()->route('horarios.index')->with('error', 'Horário em conflito com outro.');
      }
    }

    public function create()
    {
        return view('horarios.create');
    }

    public function store(Request $request)
    {
        request()->validate([
            'inicioData' => 'required|date_format:d/m',
            'fimData' => 'required|date_format:d/m',
            'inicioHora' => 'required|date_format:H:i',
            'fimHora' => 'required|date_format:H:i',
        ]);

        if($this->data_legitima($request)){
          //dd($request);
          horario::create($request->all());

          return redirect()->route('horarios.index')
                          ->with('success','Horário criado com sucesso!');
        }
        else {
          return redirect()->route('horarios.index')->with('error', 'Horário em conflito com outro.');
        }
    }

    public function destroy(horario $horario)
    {
        $horario->delete();

        return redirect()->route('horarios.index')
                        ->with('success','Horário deletado com sucesso!');
    }

    public function data_legitima(Request $request){
        $horario = $request;
        $horario_novo_inicio = Carbon::createFromFormat('d/m', ($horario->inicioData));
        $horario_novo_fim = Carbon::createFromFormat('d/m', ($horario->fimData));
        $horarios_atuais = DB::table('horarios')->where('inicioData', '!=', $horario->inicioData)->where('fimData', '!=', $horario->fimData)->get();

        $validade = TRUE;

        foreach ($horarios_atuais as $horario_atual){
          $horario_atual_inicio = Carbon::createFromFormat('d/m', $horario_atual['inicioData']);
          $horario_atual_fim = Carbon::createFromFormat('d/m', $horario_atual['fimData']);

          if($horario_novo_inicio->between($horario_atual_inicio, $horario_atual_fim)
             or $horario_novo_fim->between($horario_atual_inicio, $horario_atual_fim)){
               $validade = FALSE;
          }
        }

        return $validade;
    }
}

resources/views/horarios/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add Novo Horario</h2>
            </div>
            <div class="pull-right" style="height: 60px">
                <a class="btn btn-primary" href="{{ route('horarios.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <form action="{{ route('horarios.store') }}" method="POST">
    	@csrf
       <div class="row">
        		  <div class="col-xs-12 col-sm-12 col-md-12" style="height: 0px">
        		       <div class="form-group">
        		           <strong>Data de Início:</strong>
        		           <input type="text" style="height:40px; width: 90px" maxlength="5" name="inicioData" class="form-control">
        		       </div>
        		   </div>
        		  <div class="col-xs-12 col-sm-12 col-md-12" style="margin-left: 120px">
        		       <div class="form-group">
        		           <strong>Data Fim:</strong>
                           <input type="text" style="height:40px; width: 90px" maxlength="5" name="fimData" class="form-control">
        		       </div>
        		  </div>
              <div class="col-xs-12 col-sm-12 col-md-12" style="height: 0px">
        		     <div class="form-group">
        		           <strong>Hora de Início:</strong>
        		           <input type="text" style="height:40px; width: 90px" maxlength="5" name="inicioHora" class="form-control">
        		     </div>
        		   </div>
        		   <div class="col-xs-12 col-sm-12 col-md-12" style="margin-left: 120px">
        		     <div class="form-group">
        		           <strong>Hora Fim:</strong>
                           <input type="text" style="height:40px; width: 90px" maxlength="5" name="fimHora" class="form-control">
        		     </div>
        		   </div>
        		   <div class="col-xs-12 col-sm-12 col-md-12">
        		     <button type="submit" class="btn btn-primary">Salvar</button>
        		   </div>
        	</div>

   </form>
</div>
@endsection

resources/views/horarios/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Horario</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('horarios.index') }}">Voltar</a>
            </div>
        </div>
    </div>

    </br>
    <form action="{{ route('horarios.update',$horario->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
        		  <div class="col-xs-12 col-sm-12 col-md-12" style="height: 0px">
        		       <div class="form-group">
        		           <strong>Data de Início:</strong>
        		           <input type="text" style="height:40px; width: 90px" maxlength="5" name="inicioData" value="{{ $horario->inicioData }}" class="form-control" placeholder="Fim">
        		       </div>
        		   </div>
        		  <div class="col-xs-12 col-sm-12 col-md-12" style="margin-left: 120px">
        		       <div class="form-group">
        		           <strong>Data Fim:</strong>
                           <input type="text" style="height:40px; width: 90px" maxlength="5" name="fimData" value="{{ $horario->fimData }}" class="form-control">
        		       </div>
        		  </div>
              <div class="col-xs-12 col-sm-12 col-md-12" style="height: 0px">
        		     <div class="form-group">
        		           <strong>Hora de Início:</strong>
        		           <input type="text" style="height:40px; width: 90px" maxlength="5" name="inicioHora" value="{{ $horario->inicioHora }}" class="form-control" placeholder="Fim">
        		     </div>
        		   </div>
        		   <div class="col-xs-12 col-sm-12 col-md-12" style="margin-left: 120px">
        		     <div class="form-group">
        		           <strong>Hora Fim:</strong>
                           <input type="text" style="height:40px; width: 90px" maxlength="5" name="fimHora" value="{{ $horario->fimHora }}" class="form-control">
        		     </div>
        		   </div>
        		   <div class="col-xs-12 col-sm-12 col-md-12">
        		     <button type="submit" class="btn btn-primary">Salvar</button>
        		   </div>
        	</div>
   </form>
</div>
@endsection

resources/views/horarios/index.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left" style="margin-left: 10px">
                <h2>Horário de Funcionamento</h2>
            </div>
            <div class="pull-right" style="height: 55px; margin-left: 10px">
                <a class="btn btn-success" href="{{ route('horarios.create') }}"> Criar um novo horário</a>
            </div>
        </div>
    </div>
    <div>
        <table class="table table-bordered">
            <tr>
                <th>Data de Início</th>
                <th>Data Fim</th>
                <th>Hora de Início</th>
                <th>Hora Fim</th>
                <th width="280px"></th>
            </tr>
	        @foreach ($horarios as $horario)
	        <tr>
	           <td>{{ $horario->inicioData }}</td>
	           <td>{{ $horario->fimData }}</td>
             <td>{{ $horario->inicioHora }}</td>
	           <td>{{ $horario->fimHora }}</td>
	           <td>
                <form action="{{ route('horarios.destroy',$horario->id) }}" method="POST">
                    <a class="btn btn-primary" href="{{ route('horarios.edit',$horario->id) }}">Editar</a>
                    @method('DELETE')
                    <button class="btn btn-danger" type="submit">Deletar</button>
                    @csrf
                </form>
	           </td>
	        </tr>
	        @endforeach
        </table>
    </div>
    <a class="btn btn-secondary" href="{{ route('admin.home') }}">Voltar</a>
</div>
@endsection

resources/views/horarios/show.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add Novo Horario</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('horarios.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <form action="{{ route('horarios.store') }}" method="POST">
    	@csrf
         <div class="row">
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Inicio:</strong>
		            <input type="text" name="inicio" class="form-control" placeholder="inicio">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Fim:</strong>
		            <textarea class="form-control" style="height:150px" name="fim" placeholder="Fim"></textarea>
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		            <button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>
   </form>

@endsection