routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\TicketController;
use App\ticket;
use App\horario;
use App\cardapio;
use App\avaliacao;
use Carbon\Carbon;

Auth::routes();

Route::get('/', function () {
  if(Auth::user()){
    if(auth()->user()->is_admin == 1){
      return redirect()->route('admin.home');
    }
    else {
      return redirect()->route('home');
    }
  }
  else{
    return view('/auth/login');
  }
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin'], function(){
  Route::resource('ticket', 'TicketController')->middleware('is_admin');
  Route::resource('horarios','HorarioController')->middleware('is_admin');
  Route::resource('cardapios','CardapioController')->middleware('is_admin');
  Route::resource('alimentos', 'AlimentoController')->middleware('is_admin');
  Route::resource('avaliacao', 'AvaliacaoController');
  Route::get('/avaliacoes/','AvaliacaoController@index_total')->name('avaliacao.index_total')->middleware('is_admin');
  Route::get('/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');
  Route::get('/relatorios', 'HomeController@relatorioCompras')->name('relatorios')->middleware('is_admin');
});

Route::group(['prefix'=>'aluno'], function(){
  Route::get('/usar_ticket', 'PedidoController@alunoUsarTicket')->name('usar');
  Route::post('/saldo_add', 'PedidoController@alunoSaldoAdd')->name('alunoSaldoAdd');
  Route::get('/comprar/{ticket}', 'PedidoController@compra')->name('comprar');
  Route::get('/avaliacoes','AvaliacaoController@indexAluno')->name('aluno.avaliacoes');
  Route::get('/pedidos','PedidoController@indexPedidos')->name('aluno.pedidos');
});















































// ?
Route::get('/giomar', function () {
    return view('giomar');
})->name('giomar');

app/alimento.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class alimento extends Eloquent
{
    protected $connection = 'mongodb';
    protected $collection = 'alimentos';

    protected $fillable = ['nome', 'tipo'];
}

app/Http/Controllers/AlimentoController.php
<?php

namespace App\Http\Controllers;

use App\alimento;
use Illuminate\Http\Request;

class AlimentoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $alimentos = alimento::all()->sortBy('tipo');

      return view('alimentos.index', ['alimentos' => $alimentos])
          ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('alimentos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
          'nome' => 'required',
          'tipo' => 'required',
      ]);

      alimento::create($request->all());

      return redirect()->route('alimentos.index')
                      ->with('success','Alimento registrado com sucesso.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(alimento $alimento)
    {
        return view('alimentos.edit',compact('alimento'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, alimento $alimento)
    {
      $request->validate([
          'tipo' => 'required',
          'nome' => 'required',
      ]);

      $alimento->update($request->all());

      return redirect()->route('alimentos.index')
                      ->with('success','Alimento atualizado com sucesso.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(alimento $alimento)
    {
      $alimento->delete();

      return redirect()->route('alimentos.index')
                      ->with('success','Alimento removido com sucesso.');
    }
}

resources/views/alimentos/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Adicionar novo alimento</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('alimentos.index') }}">Back</a>
            </div>
        </div>
    </div>

    <form action="{{ route('alimentos.store') }}" method="POST">
    	@csrf
		       <strong>Tipo:</strong>
            <select class="form-control" name="tipo">
	             <option>Arroz</option>
	             <option>Feijão</option>
               <option>Carne</option>
	             <option>Suco</option>
	          </select>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Nome:</strong>
		            <textarea class="form-control" style="height:150px" name="nome" placeholder="Nome do Alimento"></textarea>
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		            <button type="submit" class="btn btn-primary">Salvar</button>
		    </div>

   </form>
</div>
@endsection

resources/views/alimentos/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Alimento</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('alimentos.index') }}">Voltar</a>
            </div>
        </div>
    </div>

    </br>
    <form action="{{ route('alimentos.update',$alimento->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
        		  <div class="col-xs-12 col-sm-12 col-md-12">
        		       <div class="form-group">
        		           <strong>Tipo:</strong>
                       <select class="form-control" name="tipo">
                         <option> {{ $alimento->tipo }} </option>
                        @if($alimento->tipo != "Arroz")
           	             <option>Arroz</option>
                        @endif
                        @if($alimento->tipo != "Feijão")
           	             <option>Feijão</option>
                        @endif
                        @if($alimento->tipo != "Carne")
                         <option>Carne</option>
                        @endif
                        @if($alimento->tipo != "Suco")
           	             <option>Suco</option>
                        @endif
           	          </select>
        		       </div>
        		   </div>
        		  <div class="col-xs-12 col-sm-12 col-md-12">
        		       <div class="form-group">
        		           <strong>Nome:</strong>
        		           <textarea class="form-control" style="height:150px" name="nome">{{ $alimento->nome }}</textarea>
        		       </div>
        		  </div>
        		   <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        		     <button type="submit" class="btn btn-primary">Salvar</button>
        		   </div>
        	</div>
   </form>
</div>
@endsection

resources/views/alimentos/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-10 margin-tb">
            <div class="pull-left" style="margin-left: 10px">
                <h2>Alimentos</h2>
            </div>
        </br>
          <div class="pull-right">
              <a class="btn btn-success" style="margin-left: 10px" href="{{ route('alimentos.create') }}">Registrar um novo alimento</a>
          </div>
        </div>
    </div>


    </br>
    <table class="table table-bordered">
        <tr>
            <th>Tipo</th>
            <th>Nome</th>
            <th width="280px">Ações</th>
        </tr>
	    @foreach ($alimentos as $alimento)
	    <tr>
            <td>{{ $alimento->tipo }}</td>
            <td>{{ $alimento->nome }}</td>
	        <td>
            <form action="{{ route('alimentos.destroy',$alimento->id) }}" method="POST">
                <a class="btn btn-primary" href="{{ route('alimentos.edit',$alimento->id) }}">Editar</a>
                @method('DELETE')
                <button class="btn btn-danger" type="submit">Deletar</button>
                @csrf
            </form>
	        </td>
	    </tr>
	    @endforeach
    </table>

    <a class="btn btn-secondary" href="{{ route('admin.home') }}">Voltar</a>
</div>
@endsection