routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\TicketController;
use App\ticket;
use App\horario;
use App\cardapio;
use App\avaliacao;
use Carbon\Carbon;

Auth::routes();

Route::get('/', function () {
  if(Auth::user()){
    if(auth()->user()->is_admin == 1){
      return redirect()->route('admin.home');
    }
    else {
      return redirect()->route('home');
    }
  }
  else{
    return view('/auth/login');
  }
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin'], function(){
  Route::resource('ticket', 'TicketController')->middleware('is_admin');
  Route::resource('horarios','HorarioController')->middleware('is_admin');
  Route::resource('cardapios','CardapioController')->middleware('is_admin');
  Route::resource('alimentos', 'AlimentoController')->middleware('is_admin');
  Route::resource('avaliacao', 'AvaliacaoController');
  Route::get('/avaliacoes/','AvaliacaoController@index_total')->name('avaliacao.index_total')->middleware('is_admin');
  Route::get('/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');
  Route::get('/relatorios', 'HomeController@relatorioCompras')->name('relatorios')->middleware('is_admin');
});

Route::group(['prefix'=>'aluno'], function(){
  Route::get('/usar_ticket', 'PedidoController@alunoUsarTicket')->name('usar');
  Route::post('/saldo_add', 'PedidoController@alunoSaldoAdd')->name('alunoSaldoAdd');
  Route::get('/comprar/{ticket}', 'PedidoController@compra')->name('comprar');
  Route::get('/avaliacoes','AvaliacaoController@indexAluno')->name('aluno.avaliacoes');
  Route::get('/pedidos','PedidoController@indexPedidos')->name('aluno.pedidos');
});















































// ?
Route::get('/giomar', function () {
    return view('giomar');
})->name('giomar');

app/cardapio.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class cardapio extends Eloquent
{
    protected $connection = 'mongodb';
    protected $collection = 'cardapios';

    protected $fillable = ['data', 'dia', 'descricao'];
}

app/Http/Controllers/CardapioController.php
<?php

namespace App\Http\Controllers;

use App\cardapio;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class CardapioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $cardapios = cardapio::all()->sortByDesc('_id');

      return view('cardapios.index', ['cardapios' => $cardapios])
          ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $arrozes = DB::collection('alimentos')->where('tipo', 'Arroz')->get();
      $feijoes = DB::collection('alimentos')->where('tipo', 'Feijão')->get();
      $carnes = DB::collection('alimentos')->where('tipo', 'Carne')->get();
      $sucos = DB::collection('alimentos')->where('tipo', 'Suco')->get();

      return view('cardapios.create', ['arrozes' => $arrozes, 'feijoes' => $feijoes, 'carnes' => $carnes, 'sucos' => $sucos]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
          'data' => 'required|date_format:d/m/Y',
          'arroz' => 'required',
          'feijao' => 'required',
          'carne' => 'required',
          'suco' => 'required',
      ]);

      foreach (cardapio::all() as $cardapio){
        if($cardapio->data == $request->data){
          return redirect()->route('cardapios.index')
                          ->with('error','O cardápio desse dia já foi registrado.');
        }
      }
      $dataTraduzida = $this->traduzir_dia(Carbon::createFromFormat('d/m/Y', $request->data)->format('l'));

      if($request->complemento){
        $descricao = $request->arroz . ', ' . $request->feijao . ', ' . $request->carne . ', ' . $request->suco . ', ' . $request->complemento . '.';
      }
      else{
        $descricao = $request->arroz . ', ' . $request->feijao . ', ' . $request->carne . ', ' . $request->suco . '.';
      }
      cardapio::create(['data' => $request->data, 'dia' => $dataTraduzida, 'descricao' => $descricao]);

      return redirect()->route('cardapios.index')
                      ->with('success','Cardápio configurado com sucesso.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\cardapio  $cardapio
     * @return \Illuminate\Http\Response
     */
    public function show(cardapio $cardapio)
    {
        return view('cardapios.show', compact('cardapio'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\cardapio  $cardapio
     * @return \Illuminate\Http\Response
     */
    public function edit(cardapio $cardapio)
    {
        $arrozes = DB::collection('alimentos')->where('tipo', 'Arroz')->get();
        $feijoes = DB::collection('alimentos')->where('tipo', 'Feijão')->get();
        $carnes = DB::collection('alimentos')->where('tipo', 'Carne')->get();
        $sucos = DB::collection('alimentos')->where('tipo', 'Suco')->get();

        $arrozAtual = explode(",", $cardapio->descricao)[0];
        $feijaoAtual = substr(explode(",", $cardapio->descricao)[1], 1);
        $carneAtual = substr(explode(",", $cardapio->descricao)[2], 1);
        if(count(explode(",", $cardapio->descricao)) == 5){
          $sucoAtual = substr(explode(",", $cardapio->descricao)[3], 1);
          $complemento = substr(explode(",", $cardapio->descricao)[4], 1, -1);
        }
        else{
          $sucoAtual = substr(explode(",", $cardapio->descricao)[3], 1, -1);
          $complemento = NULL;
        }

        return view('cardapios.edit', ['arrozes' => $arrozes, 'feijoes' => $feijoes, 'carnes' => $carnes, 'sucos' => $sucos,
        'arrozAtual' => $arrozAtual, 'feijaoAtual' => $feijaoAtual, 'carneAtual' => $carneAtual, 'sucoAtual' => $sucoAtual,
        'complemento' => $complemento, 'cardapio' => $cardapio]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\cardapio  $cardapio
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, cardapio $cardapio)
    {
      $request->validate([
          'data' => 'required|date_format:d/m/Y',
          'arroz' => 'required',
          'feijao' => 'required',
          'carne' => 'required',
          'suco' => 'required',
      ]);

      foreach (cardapio::all()->where('_id', '<>', $cardapio->_id) as $cardapioForEach){
        if($cardapioForEach->data == $request->data){
          return redirect()->route('cardapios.index')
                          ->with('error','O cardápio desse dia já foi registrado.');
        }
      }

      $dataTraduzida = $this->traduzir_dia(Carbon::createFromFormat('d/m/Y', $request->data)->format('l'));

      if($request->complemento){
        $descricao = $request->arroz . ', ' . $request->feijao . ', ' . $request->carne . ', ' . $request->suco . ', ' . $request->complemento . '.';
      }
      else{
        $descricao = $request->arroz . ', ' . $request->feijao . ', ' . $request->carne . ', ' . $request->suco . '.';
      }

      $cardapio->update(['data' => $request->data, 'dia' => $dataTraduzida, 'descricao' => $descricao]);

      return redirect()->route('cardapios.index')->with('success','Cardápio atualizado com sucesso.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\cardapio  $cardapio
     * @return \Illuminate\Http\Response
     */
    public function destroy(cardapio $cardapio)
    {
      $cardapio->delete();

      return redirect()->route('cardapios.index')
                      ->with('success','Cardápio removido com sucesso.');
    }

    public function traduzir_dia(String $dia){
      switch($dia){
        case "Monday":
          $dataTraduzida = "Segunda-Feira";
          break;
        case "Tuesday":
          $dataTraduzida = "Terça-Feira";
          break;
        case "Wednesday":
          $dataTraduzida = "Quarta-Feira";
          break;
        case "Thursday":
          $dataTraduzida = "Quinta-Feira";
          break;
        case "Friday":
          $dataTraduzida = "Sexta-Feira";
          break;
        case "Saturday":
          $dataTraduzida = "Sábado";
          break;
        case "Sunday":
          $dataTraduzida = "Domingo";
          break;
        }

      return $dataTraduzida;
    }
}

resources/views/cardapios/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Adicionar novo cardápio</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('cardapios.index') }}">Voltar</a>
            </div>
        </div>
    </div>

    <form action="{{ route('cardapios.store') }}" method="POST">
    	@csrf
       <div class="row">
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Data:</strong>
		            <input type="text" name="data" class="form-control" placeholder="Inicio">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Arroz:</strong>
                <select class="form-control" name="arroz">
                  @foreach ($arrozes as $arroz)
	                 <option>{{ $arroz['nome'] }}</option>
                  @endforeach
	              </select>
            </div>
            <div class="form-group">
                <strong>Feijão:</strong>
                <select class="form-control" name="feijao">
                  @foreach ($feijoes as $feijao)
	                 <option>{{ $feijao['nome'] }}</option>
                  @endforeach
	              </select>
            </div>
            <div class="form-group">
		            <strong>Carne:</strong>
                <select class="form-control" name="carne">
                  @foreach ($carnes as $carne)
	                 <option>{{ $carne['nome'] }}</option>
                  @endforeach
	              </select>
            </div>
            <div class="form-group">
                <strong>Suco:</strong>
                <select class="form-control" name="suco">
                  @foreach ($sucos as $suco)
	                 <option>{{ $suco['nome'] }}</option>
                  @endforeach
	              </select>
            </div>
		    </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Complemento Opcional:</strong>
		            <input type="text" name="complemento" class="form-control" placeholder="Complemento">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		            <button type="submit" class="btn btn-primary">Salvar</button>
		    </div>
		</div>

   </form>
</div>
@endsection

resources/views/cardapios/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Cardápio</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('cardapios.index') }}"> Voltar</a>
            </div>
        </div>
    </div>

    </br>
    <form action="{{ route('cardapios.update',$cardapio->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
        		  <div class="col-xs-12 col-sm-12 col-md-12">
        		       <div class="form-group">
        		           <strong>Data:</strong>
        		           <input type="text" name="data" value="{{ $cardapio->data }}" class="form-control" placeholder="Fim">
        		       </div>
        		   </div>
               <div class="col-xs-12 col-sm-12 col-md-12">
       		        <div class="form-group">
       		            <strong>Arroz:</strong>
                       <select name="arroz">
                         <option>{{ $arrozAtual }}</option>
                         @foreach ($arrozes as $arroz)
                          @if($arroz['nome'] != $arrozAtual)
       	                   <option>{{ $arroz['nome'] }}</option>
                          @endif
                         @endforeach
       	              </select>
                   </div>
                   <div class="form-group">
                       <strong>Feijão:</strong>
                       <select name="feijao">
                         <option>{{ $feijaoAtual }}</option>
                         @foreach ($feijoes as $feijao)
                          @if($feijao['nome'] != $feijaoAtual)
       	                   <option>{{ $feijao['nome'] }}</option>
                          @endif
                         @endforeach
       	              </select>
                   </div>
                   <div class="form-group">
        		            <strong>Carne:</strong>
                        <select name="carne">
                          <option>{{ $carneAtual }}</option>
                          @foreach ($carnes as $carne)
                           @if($carne['nome'] != $carneAtual)
        	                   <option>{{ $carne['nome'] }}</option>
                           @endif
                          @endforeach
        	              </select>
                    </div>
                   <div class="form-group">
                       <strong>Suco:</strong>
                       <select name="suco">
                         <option>{{ $sucoAtual }}</option>
                         @foreach ($sucos as $suco)
                          @if($suco['nome'] != $sucoAtual)
       	                   <option>{{ $suco['nome'] }}</option>
                          @endif
                         @endforeach
       	              </select>
                   </div>
       		    </div>
               <div class="col-xs-12 col-sm-12 col-md-12">
       		        <div class="form-group">
       		            <strong>Complemento Opcional:</strong>
       		            <input type="text" name="complemento" class="form-control" placeholder="Complemento" value="{{ $complemento }}">
       		        </div>
       		    </div>
        		   <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        		     <button type="submit" class="btn btn-primary">Salvar</button>
        		   </div>
        	</div>
   </form>
</div>
@endsection

resources/views/cardapios/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-10 margin-tb">
            <div class="pull-left" style="margin-left: 11px">
                <h2>Cardápios</h2>
            </div>
        </br>
          <div class="pull-right">
              <a class="btn btn-success" style="margin-left: 11px" href="{{ route('cardapios.create') }}">Registrar um novo cardápio</a>
          </div>
        </div>
    </div>


    </br>
    <table class="table table-bordered">
        <tr>
            <th>Data</th>
            <th>Dia</th>
            <th>Descrição</th>
            <th width="280px">Ações</th>
        </tr>
	    @foreach ($cardapios as $cardapio)
	    <tr>
            <td>{{ $cardapio->data }}</td>
            <td>{{ $cardapio->dia }}</td>
            <td>{{ $cardapio->descricao }}</td>
	        <td>
            <form action="{{ route('cardapios.destroy',$cardapio->id) }}" method="POST">
                <a class="btn btn-primary" href="{{ route('cardapios.edit',$cardapio->id) }}">Editar</a>
                @method('DELETE')
                <button class="btn btn-danger" type="submit">Deletar</button>
                @csrf
            </form>
	        </td>
	    </tr>
	    @endforeach
    </table>

    <a class="btn btn-secondary" href="{{ route('admin.home') }}">Voltar</a>
</div>
@endsection